# Generated by Django 3.1.1 on 2020-09-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.CharField(default='samuel', max_length=150),
            preserve_default=False,
        ),
    ]
